Repository OSCode-Community/OSCodeCommunitySite, pull requests merged in 2023-07, with the labels that each got.

#968 Fixed Navbar issue
  chapters/chapter.html
  index.html
Labels: gssoc23, level1

#1022 Adding navbar and make the page responsive
  assets/css/about.css
  assets/css/services.css
  assets/css/style.css
  services.html
Labels: gssoc23, level2

#1078 Added whatapp and added event link in index.html
  assets/gallery.html
  contact/contact.html
  events/events.html
  index.html
Labels: gssoc23, level1

#1058 Fix issue #1044: Added hover effect on github link
  assets/css/style.css
  index.html
Labels: gssoc23, level1

#1056 Added firebase authentication to the website
  assets/css/login.css
  assets/css/override.css
  assets/css/resetpass.css
  assets/css/signup.css
  assets/css/style.css
  firebase/firebase.js
  login/login.html
  login/login.js
  signup/signup.html
  signup/signup.js
Labels: gssoc23

#1398 Workflow to Reduce Notifications 🚀
  .github/workflows/lock.yml
Labels: gssoc23, level3

#1425 Update services.html
  services.html
Labels: gssoc23, level2
