Repository OSCode-Community/OSCodeCommunitySite, pull requests merged in 2023-08, with the labels that each got.

#1546 Event page navbar toggle button is not visible on mobile view
  assets/css/events.css
  assets/css/services.css
  assets/css/style.css
  events/event.css
  events/events.html
Labels: gssoc23, level1

#1555 button is updated and the removed scroll bar
  assets/css/login.css
  login/login.html
Labels: gssoc23, level2

#1457 feat: automating author assign pr to author 💡
  .github/workflows/pr-author-assign.yml
Labels: gssoc23, level3

#1563 madesociallinksinsingleline
  assets/css/override.css
  assets/css/style.css
  contributors/contributor.html
Labels: gssoc23, level2

#1569 home page style changed
  assets/css/join_us.css
  assets/css/style.css
Labels: gssoc23, level2

#1572 now it scrolls down to events section
  events/events.html
Labels: gssoc23, level1

#1565 [Feat]Added background animation in contributors page.
  contributors/style.css
Labels: gssoc23, level2

#1562 [Bug]:Updated logo and text overlapping in footer in Contacts Page [GSSoC'23]
  contact/contact.html
Labels: gssoc23, level1

#1559 assresschanged
  assets/css/contact.css
  assets/css/contactform.css
  index.html
Labels: gssoc23, level2

#1557 addedimageatcorrectplace
  assets/css/style.css
  chapters/css/styles.css
Labels: gssoc23, level1

#850 MissingIconAdded
  chapters/chapter.html
  events/events.html
Labels: gssoc23, level2

#852 Heading styling
  assets/css/chapter.css
  chapters/chapter.html
  events/events.html
Labels: gssoc23, level2

#1581 updated contributor page
  contributors/style.css
Labels: gssoc23, level2

#1542 Refactor JavaScript code for Signup.js ✨
  signup/signup.js
Labels: gssoc23, level2

#1591 preloader updated
  policy/policy.html
Labels: gssoc23, level2

#1583 changing background {video attached}
  assets/css/style.css
  assets/img/imgg.jpg
  assets/img/team.jpg
  assets/img/watch.jpg
  index.html
Labels: gssoc23, level2

#904 Responsive
  assets/css/chapter.css
  chapters/chapter.html
  chapters/instituteImages/bit.png
  chapters/instituteImages/dsce.png
  chapters/instituteImages/sambhram.jpeg
  chapters/instituteImages/sirmvit.jpg
  chapters/instituteImages/sjc.jpg
  chapters/instituteImages/srikrishna.png
  chapters/instituteImages/vemana.jpg
Labels: gssoc23, level2

#1596 login and signup page button improved
  assets/css/login.css
  assets/css/signup.css
  signup/signup.html
Labels: gssoc23, level2

#1613 overlapping button fixed
  assets/css/style.css
Labels: gssoc23, level1

#1606 [docs]: Improve contributing.md guide #1540
  CONTRIBUTING.md
Labels: gssoc23, level2

#1538 refactor: contributors.js with best practices ✨
  contributors/contributor.html
  contributors/contributors.js
  contributors/style.js
Labels: gssoc23, level2

#1600 numbers section made responsive {ss added}
  assets/css/style.css
Labels: gssoc23, level2

#1617 Updated footer in all the pages
  assets/gallery.html
  contributors/contributor.html
  events/events.html
  index.html
Labels: gssoc23, level1

#1587 BUG is resolved in chapter section as well as at EVENT PAGE
  assets/css/chapter.css
  chapters/chapter.html
  events/events.html
Labels: gssoc23, level2

#1605 Navbar is not same for every page
  contributors/contributor.html
  login/login.html
  signup/signup.html
Labels: gssoc23, level2

#1629 our accomplishment section made responsive
  assets/css/style.css
Labels: gssoc23, level2

#1615 chapter page improved
  assets/css/chapter.css
  chapters/chapter.html
Labels: gssoc23, level3

#902 Image cards
  assets/css/chapter.css
  chapters/chapter.html
Labels: gssoc23, level3

#1636 privacy policy header updated
  assets/css/privacy.css
  policy/policy.html
Labels: gssoc23, level1

#906 Our services
  assets/css/chapter.css
  assets/css/services.css
  chapters/chapter.html
  services.html
Labels: gssoc23, level2

#1633 feat: Added Multiple Workflows in GitHub Workflows Folder
  .github/workflows/auto_issue_assign.yml
  .github/workflows/issue_close_greet.yml
  .github/workflows/issues.yml
  .github/workflows/pr_auto_comment.yml
  .github/workflows/pr_close_greet.yml
  .github/workflows/prevent_multiple_issues.yml
Labels: gssoc23, level2

#1630 feat: Added styles.yml File in GitHub Issue Templates
  .github/ISSUE_TEMPLATE/styles.yml
Labels: gssoc23, level3

#1632 fix: Added ARIA attributes and Other attributes in Suitable 10 HTML Files
  assets/gallery.html
  chapters/bit.html
  chapters/chapter.html
  contact/contact.html
  contributors/contributor.html
  events/events.html
  index.html
  login/login.html
  resetpass/resetpass.html
  signup/signup.html
Labels: gssoc23, level2

#1635 box shadow added on back to top only on hovering
  assets/css/style.css
Labels: gssoc23, level2
