Repository OSCode-Community/OSCodeCommunitySite, pull requests merged in 2023-06, with the labels that each got.

#533 Adding hovering effect on discord logo in footer
  assets/css/style.css
Labels: gssoc23, level1

#509 get started and services button made little larger
  assets/css/style.css
Labels: gssoc23

#571 footer issue fixed
  assets/css/chapter.css
  assets/css/events.css
  assets/css/override.css
  assets/css/style.css
  chapters/chapter.html
  events/events.html
  index.html
Labels: gssoc23

#577 added validatation and required field
  index.html
Labels: gssoc23

#628 Made Accomplishment Section Responsive [Closes #610]
  assets/css/style.css
Labels: gssoc23

#797 fixed issue #796
  assets/css/about.css
  assets/css/style.css
  index.html
Labels: gssoc23, level2
