Repository OSCode-Community/OSCodeCommunitySite, pull requests merged in 2023-05, with the labels that each got.

#448 [testimonial item class] Responsiveness Issue of text overflowing out of the placards solved
  assets/css/style.css
Labels: gssoc23

#461 #460 issue solved
  assets/css/style.css
  chapters/chapter.html
  events/events.html
Labels: gssoc23, level3

#466 Added 3d effect to the title with some text shadow
  assets/css/style.css
Labels: gssoc23, level1

#477 #472 and #476 solved
  assets/css/override.css
  assets/css/style.css
  events/events.html
  index.html
Labels: gssoc23

#491 Updated "Join Us" Section
  assets/css/style.css
  index.html
Labels: gssoc23

#490 Updated ReadMe file
  README.md
Labels: gssoc23

#531 added slider to accomplishments
  index.html
Labels: gssoc23

#536 updated Navbar On scrolling #498
  assets/css/navbarUi.css
  assets/css/override.css
  assets/css/style.css
  index.html
Labels: gssoc23
